export * from './locations.js';
export * from './items.js';
export * from './skills.js';
export * from './recipes.js';
export * from './collections.js';
export * from './inventory.js';
export * from './minions.js';
export * from './protocol.js';
export * from './stats.js';
export * from './lore.js';
export * from './enchantments.js';
export * from './content.js';
export * from './world.js';
export * from './islandBuild.js';
export * from './bazaarCategories.js';
export * from './dungeonContent.js';
export * from './dungeonPlay.js';
export * from './dungeonMap.js';
export * from './accessories.js';
export * from './worldCombat.js';
export * from './quests.js';
export * from './questChains.js';
export * from './dailies.js';
export * from './shops.js';
export * from './drill.js';
export * from './forge.js';
export * from './playerLocation.js';
export * from './midgame.js';
export * from './economy.js';
export * from './seaCreatures.js';
export * from './gardenPlots.js';
export * from './enchantProcs.js';
import './registerCatalog.js';
import './registerGear.js';
import './registerSkyblockRecipes.js';
import './registerForge.js';

export const GAME_NAME = 'Aether Isles';
export const TICK_MS = 100;
export const PRESENCE_HZ = 10;
export const MAX_HP = 100;
export const MOVE_SPEED = 4.5; // tiles per second
export const STARTER_COINS = 100;
