import type { ItemId } from './items.js';

/**
 * Hypixel SkyBlock NPC sell prices (coins when selling to a merchant).
 * Sourced from https://hypixel-skyblock.fandom.com/wiki/List_of_Item_Prices
 * — farming table on the main page + Item Prices subpage.
 * Enchanted tiers use wiki values where listed, otherwise base × 160.
 */
export const NPC_SELL_PRICES: Partial<Record<ItemId, number>> = {
  // Mining — ores & stone
  cobble: 1,
  coal: 2,
  iron_ore: 3,
  iron_ingot: 3,
  gold_ingot: 4,
  diamond: 8,
  emerald: 6,
  lapis: 1,
  redstone: 1,
  mithril: 8,
  titanium: 8,
  obsidian: 12,
  quartz: 4,
  glowstone_dust: 2,
  end_stone: 2,
  hard_stone: 1,
  netherrack: 1,
  gravel: 3,
  flint: 1,
  sand: 2,
  red_sand: 2,
  ice: 1,
  packed_ice: 1,
  snowball: 1,
  gemstone_ruby: 3,
  gemstone_jade: 3,
  gemstone_sapphire: 3,
  gemstone_amber: 3,
  gemstone_topaz: 3,
  gemstone_jasper: 3,
  sulphur: 4,
  mycelium: 2,

  // Farming
  wheat: 6,
  seeds: 3,
  carrot: 3,
  potato: 3,
  poisonous_potato: 10,
  pumpkin: 10,
  melon: 2,
  melon_slice: 2,
  sugar_cane: 4,
  cocoa_beans: 3,
  cactus: 4,
  nether_wart: 4,
  mushroom: 10,
  brown_mushroom: 4,
  red_mushroom: 4,
  leather: 3,
  feather: 3,
  raw_beef: 4,
  raw_porkchop: 5,
  raw_chicken: 4,
  raw_rabbit: 4,
  mutton: 5,
  egg: 3,
  wool: 3,
  rabbit_hide: 5,
  rabbit_foot: 5,
  hay_bale: 9,

  // Foraging
  oak_log: 2,
  spruce_log: 2,
  birch_log: 2,
  jungle_log: 2,
  acacia_log: 2,
  dark_oak_log: 2,
  oak_plank: 0.5,
  stick: 0.3,

  // Combat drops
  rotten_flesh: 2,
  bone: 2,
  string: 3,
  spider_eye: 3,
  gunpowder: 4,
  ender_pearl: 10,
  blaze_rod: 10,
  blaze_powder: 5,
  slimeball: 5,
  magma_cream: 8,
  ghast_tear: 16,
  soul_sand: 2,

  // Fishing
  raw_fish: 6,
  raw_salmon: 5,
  cooked_fish: 8,
  cooked_salmon: 6,
  clownfish: 20,
  pufferfish: 15,
  prismarine_shard: 5,
  prismarine_crystals: 5,
  sponge: 50,
  lily_pad: 10,
  ink_sack: 2,

  // Enchanted materials
  enchanted_acacia_log: 320,
  enchanted_birch_log: 320,
  enchanted_blaze_rod: 1600,
  enchanted_bone: 320,
  enchanted_bread: 60,
  enchanted_brown_mushroom: 640,
  enchanted_cactus: 640,
  enchanted_carrot: 480,
  enchanted_coal: 320,
  enchanted_coal_block: 51200,
  enchanted_cobble: 160,
  enchanted_cobble_block: 25600,
  enchanted_cocoa_beans: 480,
  enchanted_dark_oak_log: 320,
  enchanted_diamond: 1280,
  enchanted_diamond_block: 204800,
  enchanted_emerald: 960,
  enchanted_emerald_block: 153600,
  enchanted_ender_pearl: 1600,
  enchanted_eye_of_ender: 3520,
  enchanted_feather: 480,
  enchanted_ghast_tear: 2560,
  enchanted_glowstone: 320,
  enchanted_gold_block: 102400,
  enchanted_gold_ingot: 640,
  enchanted_gravel: 480,
  enchanted_gunpowder: 640,
  enchanted_iron: 480,
  enchanted_iron_block: 76800,
  enchanted_iron_ingot: 480,
  enchanted_jungle_log: 320,
  enchanted_lapis: 160,
  enchanted_lapis_block: 25600,
  enchanted_leather: 480,
  enchanted_magma_cream: 1280,
  enchanted_melon: 320,
  enchanted_mushroom: 1600,
  enchanted_mutton: 800,
  enchanted_nether_wart: 640,
  enchanted_netherrack: 160,
  enchanted_oak: 320,
  enchanted_obsidian: 1920,
  enchanted_potato: 480,
  enchanted_prismarine_crystals: 800,
  enchanted_prismarine_shard: 800,
  enchanted_pumpkin: 1600,
  enchanted_quartz: 640,
  enchanted_raw_beef: 640,
  enchanted_raw_chicken: 640,
  enchanted_raw_fish: 960,
  enchanted_raw_porkchop: 800,
  enchanted_raw_rabbit: 640,
  enchanted_raw_salmon: 800,
  enchanted_red_mushroom: 640,
  enchanted_redstone: 160,
  enchanted_redstone_block: 25600,
  enchanted_rotten_flesh: 320,
  enchanted_sand: 320,
  enchanted_seeds: 480,
  enchanted_slimeball: 800,
  enchanted_spider_eye: 480,
  enchanted_spruce_log: 320,
  enchanted_string: 576,
  enchanted_sugar_cane: 640,
  enchanted_wheat: 960,

  // Shop gear buyback
  wooden_sword: 2,
  stone_sword: 4,
  stone_pickaxe: 4,
  iron_pickaxe: 4,
  golden_pickaxe: 6,
  diamond_sword: 8,
  iron_helmet: 12,
  iron_chestplate: 20,
  iron_leggings: 18,
  iron_boots: 10,
  diamond_helmet: 40,
  diamond_chestplate: 64,
  diamond_leggings: 56,
  diamond_boots: 32,
  wooden_pickaxe: 2,
  wooden_axe: 2,
  wooden_hoe: 2,
  stone_axe: 4,
  fishing_rod: 2,
  undead_sword: 5,
  spider_sword: 5,
  cleaver: 8,
  end_sword: 10,
  fancy_sword: 50,
  silver_fang: 2500,
  shortbow: 200,

  // Other
  coal_block: 18,
  diamond_block: 72,
  emerald_block: 54,
  gold_ore: 3,
  lapis_block: 9,
};

/** Apply catalog NPC sell prices onto registered items. */
export function applyNpcSellPrices(items: Record<ItemId, { npcSell?: number }>): void {
  for (const [id, price] of Object.entries(NPC_SELL_PRICES)) {
    if (items[id]) items[id].npcSell = price;
  }
}

export function skyblockNpcSellPrice(itemId: ItemId): number | undefined {
  return NPC_SELL_PRICES[itemId];
}
