import type { CatalogEntry } from './skyblockCatalog.js';

/** Additional Hypixel SkyBlock bazaar commodities and resources. */
export const SKYBLOCK_CATALOG_EXTRA: CatalogEntry[] = [
  // Farming extras
  { id: 'bread', name: 'Bread', collection: 'farming', color: '#c4a35a', enchanted: true, minion: false },
  { id: 'cookie', name: 'Cookie', collection: 'farming', color: '#aa7744', enchanted: true, minion: false },
  { id: 'hay_bale', name: 'Hay Bale', collection: 'farming', color: '#d4b84a', enchanted: false, minion: false },
  { id: 'apple', name: 'Apple', collection: 'farming', color: '#cc3333', enchanted: true, minion: false },
  { id: 'golden_carrot', name: 'Golden Carrot', collection: 'farming', color: '#ffaa00', enchanted: true, minion: false },
  { id: 'golden_apple', name: 'Golden Apple', collection: 'farming', color: '#ffcc00', enchanted: true, minion: false },
  { id: 'enchanted_golden_apple', name: 'Enchanted Golden Apple', collection: 'farming', color: '#ff8800', enchanted: false, minion: false, bazaarable: true },
  { id: 'pumpkin_seeds', name: 'Pumpkin Seeds', collection: 'farming', color: '#ffaa00', enchanted: true, minion: false },
  { id: 'melon_seeds', name: 'Melon Seeds', collection: 'farming', color: '#55ff55', enchanted: true, minion: false },
  { id: 'beetroot', name: 'Beetroot', collection: 'farming', color: '#aa0033', enchanted: true, minion: false },
  { id: 'beetroot_seeds', name: 'Beetroot Seeds', collection: 'farming', color: '#880022', enchanted: true, minion: false },
  { id: 'ink_sack', name: 'Ink Sack', collection: 'farming', color: '#222222', enchanted: true, minion: false },
  { id: 'lily_pad', name: 'Lily Pad', collection: 'farming', color: '#228822', enchanted: true, minion: false },
  { id: 'cactus_green', name: 'Cactus Green', collection: 'farming', color: '#228822', enchanted: true, minion: false },
  { id: 'sugar', name: 'Sugar', collection: 'farming', color: '#ffffff', enchanted: true, minion: false },
  { id: 'stick', name: 'Stick', collection: 'farming', color: '#886644', enchanted: true, minion: false },
  { id: 'oak_sapling', name: 'Oak Sapling', collection: 'farming', color: '#55aa33', enchanted: true, minion: false },
  { id: 'birch_sapling', name: 'Birch Sapling', collection: 'farming', color: '#88cc88', enchanted: true, minion: false },
  { id: 'spruce_sapling', name: 'Spruce Sapling', collection: 'farming', color: '#446633', enchanted: true, minion: false },
  { id: 'jungle_sapling', name: 'Jungle Sapling', collection: 'farming', color: '#55aa33', enchanted: true, minion: false },
  { id: 'acacia_sapling', name: 'Acacia Sapling', collection: 'farming', color: '#cc6633', enchanted: true, minion: false },
  { id: 'dark_oak_sapling', name: 'Dark Oak Sapling', collection: 'farming', color: '#443311', enchanted: true, minion: false },

  // Mining extras
  { id: 'stone', name: 'Stone', collection: 'mining', color: '#888888', enchanted: true, minion: false },
  { id: 'clay_ball', name: 'Clay Ball', collection: 'mining', color: '#8888aa', enchanted: true, minion: false },
  { id: 'clay', name: 'Clay', collection: 'mining', color: '#8888aa', enchanted: true, minion: false },
  { id: 'dirt', name: 'Dirt', collection: 'mining', color: '#886644', enchanted: true, minion: false },
  { id: 'glowstone', name: 'Glowstone', collection: 'mining', color: '#ffcc44', enchanted: true, minion: false },
  { id: 'quartz_block', name: 'Quartz Block', collection: 'mining', color: '#eeeeee', enchanted: true, minion: false },
  { id: 'nether_brick', name: 'Nether Brick', collection: 'mining', color: '#442222', enchanted: true, minion: false },
  { id: 'magma_block', name: 'Magma Block', collection: 'mining', color: '#ff4400', enchanted: true, minion: false },
  { id: 'slime_block', name: 'Slime Block', collection: 'mining', color: '#55ff55', enchanted: true, minion: false },
  { id: 'tungsten', name: 'Tungsten', collection: 'mining', color: '#aaaaaa', enchanted: true, minion: false },
  { id: 'starfall', name: 'Starfall', collection: 'mining', color: '#ffffaa', enchanted: true, minion: false },
  { id: 'treasure', name: 'Treasure', collection: 'mining', color: '#ffaa00', enchanted: true, minion: false },
  { id: 'glacite', name: 'Glacite', collection: 'mining', color: '#aaddff', enchanted: true, minion: false },
  { id: 'volta', name: 'Volta', collection: 'mining', color: '#ffff55', enchanted: true, minion: false },
  { id: 'onyx', name: 'Onyx', collection: 'mining', color: '#222222', enchanted: true, minion: false },
  { id: 'peridot', name: 'Peridot', collection: 'mining', color: '#88cc44', enchanted: true, minion: false },
  { id: 'citrine', name: 'Citrine', collection: 'mining', color: '#ffcc44', enchanted: true, minion: false },
  { id: 'aquamarine', name: 'Aquamarine', collection: 'mining', color: '#44ccff', enchanted: true, minion: false },

  // Combat extras
  { id: 'wolf_tooth', name: 'Wolf Tooth', collection: 'combat', color: '#eeeeee', enchanted: true, minion: false },
  { id: 'summoning_eye', name: 'Summoning Eye', collection: 'combat', color: '#aa00ff', enchanted: true, minion: false },
  { id: 'dragon_fragment', name: 'Dragon Fragment', collection: 'combat', color: '#aa44ff', enchanted: true, minion: false },
  { id: 'golden_teeth', name: 'Golden Teeth', collection: 'combat', color: '#ffcc00', enchanted: true, minion: false },
  { id: 'rev_flesh', name: 'Revenant Flesh', collection: 'combat', color: '#6b8f4e', enchanted: true, minion: false },
  { id: 'tarantula_web', name: 'Tarantula Web', collection: 'combat', color: '#eeeeee', enchanted: true, minion: false },
  { id: 'null_sphere', name: 'Null Sphere', collection: 'combat', color: '#440044', enchanted: true, minion: false },
  { id: 'derelict_ashe', name: 'Derelict Ashe', collection: 'combat', color: '#ff8844', enchanted: true, minion: false },
  { id: 'wither_essence', name: 'Wither Essence', collection: 'combat', color: '#444444', enchanted: true, minion: false },
  { id: 'undead_catalyst', name: 'Undead Catalyst', collection: 'combat', color: '#888888', enchanted: true, minion: false },
  { id: 'revenant_catalyst', name: 'Revenant Catalyst', collection: 'combat', color: '#55aa55', enchanted: true, minion: false },
  { id: 'spider_catalyst', name: 'Spider Catalyst', collection: 'combat', color: '#aa0000', enchanted: true, minion: false },
  { id: 'wolf_catalyst', name: 'Wolf Catalyst', collection: 'combat', color: '#cccccc', enchanted: true, minion: false },
  { id: 'enderman_catalyst', name: 'Enderman Catalyst', collection: 'combat', color: '#aa00aa', enchanted: true, minion: false },
  { id: 'blaze_ashes', name: 'Blaze Ashes', collection: 'combat', color: '#ff8844', enchanted: true, minion: false },
  { id: 'match_sticks', name: 'Match Sticks', collection: 'combat', color: '#ffaa00', enchanted: true, minion: false },
  { id: 'yeti_soul', name: 'Yeti Soul', collection: 'combat', color: '#aaddff', enchanted: true, minion: false },
  { id: 'enchanted_ender_pearl', name: 'Enchanted Ender Pearl', collection: 'combat', color: '#00aaaa', enchanted: false, minion: false, bazaarable: true },

  // Woods & fishing extras
  { id: 'tropical_fish', name: 'Tropical Fish', collection: 'fishing', color: '#ff8844', enchanted: true, minion: false },
  { id: 'cod', name: 'Cod', collection: 'fishing', color: '#7ec8e3', enchanted: true, minion: false },
  { id: 'salmon', name: 'Salmon', collection: 'fishing', color: '#cc6644', enchanted: true, minion: false },
  { id: 'ink_sac', name: 'Ink Sac', collection: 'fishing', color: '#222222', enchanted: true, minion: false },
  { id: 'glow_ink_sac', name: 'Glow Ink Sac', collection: 'fishing', color: '#aaffaa', enchanted: true, minion: false },
  { id: 'nautilus_shell', name: 'Nautilus Shell', collection: 'fishing', color: '#ddccaa', enchanted: true, minion: false },
  { id: 'heart_of_the_mountain', name: 'Heart of the Mountain', collection: 'mining', color: '#ff4444', enchanted: true, minion: false },
  { id: 'crimson_stem', name: 'Crimson Stem', collection: 'foraging', color: '#aa2233', enchanted: true, minion: false },
  { id: 'warped_stem', name: 'Warped Stem', collection: 'foraging', color: '#22aaaa', enchanted: true, minion: false },
  { id: 'crimson_planks', name: 'Crimson Planks', collection: 'foraging', color: '#882233', enchanted: true, minion: false },
  { id: 'warped_planks', name: 'Warped Planks', collection: 'foraging', color: '#228888', enchanted: true, minion: false },
  { id: 'stripped_oak_log', name: 'Stripped Oak Log', collection: 'foraging', color: '#aa7744', enchanted: true, minion: false },
  { id: 'stripped_spruce_log', name: 'Stripped Spruce Log', collection: 'foraging', color: '#553311', enchanted: true, minion: false },
  { id: 'stripped_birch_log', name: 'Stripped Birch Log', collection: 'foraging', color: '#ddddaa', enchanted: true, minion: false },
  { id: 'stripped_jungle_log', name: 'Stripped Jungle Log', collection: 'foraging', color: '#aa7733', enchanted: true, minion: false },
  { id: 'stripped_acacia_log', name: 'Stripped Acacia Log', collection: 'foraging', color: '#cc6633', enchanted: true, minion: false },
  { id: 'stripped_dark_oak_log', name: 'Stripped Dark Oak Log', collection: 'foraging', color: '#443311', enchanted: true, minion: false },

  // Oddities / refined goods
  { id: 'enchanted_book', name: 'Enchanted Book', collection: 'combat', color: '#8844ff', enchanted: false, minion: false, bazaarable: true },
  { id: 'experience_bottle', name: 'Experience Bottle', collection: 'combat', color: '#55ff55', enchanted: true, minion: false },
  { id: 'grand_experience_bottle', name: 'Grand Experience Bottle', collection: 'combat', color: '#55ff55', enchanted: false, minion: false, bazaarable: true },
  { id: 'titan_experience_bottle', name: 'Titan Experience Bottle', collection: 'combat', color: '#55ff55', enchanted: false, minion: false, bazaarable: true },
  { id: 'super_egg', name: 'Super Enchanted Egg', collection: 'farming', color: '#ffffaa', enchanted: false, minion: false, bazaarable: true },
  { id: 'omni_egg', name: 'Omni-Archaeologist Egg', collection: 'farming', color: '#ffffaa', enchanted: false, minion: false, bazaarable: false },
  { id: 'hot_potato_book', name: 'Hot Potato Book', collection: 'farming', color: '#ff8800', enchanted: false, minion: false, bazaarable: true },
  { id: 'recombobulator_3000', name: 'Recombobulator 3000', collection: 'mining', color: '#55ffff', enchanted: false, minion: false, bazaarable: true },
  { id: 'dungeon_chest_key', name: 'Dungeon Chest Key', collection: 'combat', color: '#ffaa00', enchanted: false, minion: false, bazaarable: false },
];
